#!/bin/bash

# compile using tsconfig.json
tsc

# minify the compiled version
uglifyjs build/eendraadschema.js > build/eendraadschema.min.js

# adding the GPL is pointless then
#cat build/GPL3.js build/eendraadschema_no_gpl.js > eendraadschema.js

# update builddate
echo "var CONF_builddate=\""`date +%Y%m%d-%H%M%S`"\"" > build/builddate.js
