#!/bin/bash

# compile using tsconfig.json
tsc -b build

# add GPL
cat build/GPL3.js build/eendraadschema_no_gpl.js > eendraadschema.js

# update builddate
echo "var CONF_builddate=\""`date +%Y%m%d-%H%M%S`"\"" > builddate.js
